apiVersion: v1
kind: cypress
defaults: {}
showConsoleLog: false
sauce:
  region: us-west-1
  concurrency: 4
  sauceignore: .sauceignore
env:
    SAUCE_USERNAME: $SAUCE_USERNAME
    SAUCE_ACCESS_KEY: $SAUCE_ACCESS_KEY
cypress:
  configFile: cypress.config.js
  version: 13.6.3
  record: false
  key: ""
  reporters: []
npm:
  packages:
    "@saucelabs/cypress-visual-plugin": "latest"
suites:
- name: macOS 13 - chrome
  browser: chrome
  platformName: macOS 13
  screenResolution: "2048x1536"
  config:
    testingType: e2e
    specPattern: [ "cypress/e2e/**/*.*" ]
    # excludeSpecPattern: ["cypress/e2e/checkMeta.cy.js"]
rootDir: .
artifacts:
  download:
    match:
    - '*'
    when: never
    directory: ./artifacts
